version: "3.9"
services:
  client:
    container_name: react
    build: ./client
    ports:
      - 3001:3000

  server:
    container_name: node
    build: ./server
    ports:
      - 3002:3002
    environment:
      - DB=mongodb://mango:27017
    depends_on:
      - mango

  mango:
    image: mongo
    restart: always
    ports:
      - 2717:27017

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
