services:
  frontend:
    container_name: testfromtend
    build: ./client
    ports:
      - 3001:3000
  backend:
    container_name: testbackend
    build: ./server
    ports:
      - 3002:3002
